### ISSUE TITLE
compiling on win xp 32bit

### ISSUE THREAD

**Issue by gotohr** [pbnjay/memory#4]
as title says, I'm trying to compile on said platform, could you please share your build process you did for win 7?

**Comment by pbnjay** [comment]
Shouldn't be anything different from standard go build process. I don't do a lot of windows programming, but I wouldn't be surprised if XP didn't have the APIs used. FYI Go doesn't officially support windows XP past Go 1.10.7: https://github.com/golang/go/wiki/Windows

If you have a working go install on XP, the following should just work (again assuming APIs are present):

    $ go get github.com/pbnjay/memory
    $ go test -v github.com/pbnjay/memory
    === RUN   TestNonZero
    --- PASS: TestNonZero (0.00s)
    PASS
    ok  	github.com/pbnjay/memory
