### ISSUE TITLE
add a license?

### ISSUE THREAD

**Issue by flyinprogrammer** [pbnjay/memory#5]
Any chance you'd be willing to add a license to this code, so that I can legally use it other projects? Perhaps [Apache License 2.0](https://choosealicense.com/licenses/apache-2.0/) or [MIT](https://choosealicense.com/licenses/mit/)?

I'd be more happy to submit a PR with the appropriate changes.

**Comment by pbnjay** [comment]
Hey sorry I must have missed this during the holidays. I had submitted it as a PR to the stdlib, so I'll put it in a BSD license since that's basically what it would have been under anyway.
